version: 2
jobs:
  test:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - restore_cache:
          key: hcsp-{{ checksum "pom.xml" }}
      - run:
          name: Verify whitelist
          command: ./.circleci/verifyWhitelist.sh
      - run:
          name: Verify the poem is correct
          command: grep '地上霜' -r . --include=静夜思.txt
      - run:
          name: Wait a while
          command: sleep 5
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: hcsp-{{ checksum "pom.xml" }}
workflows:
  version: 2
  default:
    jobs:
      - test
