version: 2
jobs:
  test:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Verify whitelist
          command: ./.circleci/verifyWhitelist.sh
      - run:
          name: Verify the poem is correct
          command: grep '地上霜' -r . --include=静夜思.txt
workflows:
  version: 2
  default:
    jobs:
      - test
